### ISSUE TITLE
Test changing of MAKE_GRID_TN to something other than default value

### ISSUE THREAD

**Issue by gsketefian** [ufs-community/regional_workflow#430]
Tried once on the release branch, failed (forgot in which task), seemingly related to yaml configuration (the settings variable in one of the tasks, can't remember which).

**Comment by mkavulich** [comment]
I can confirm that changing MAKE_GRID_TN results in a failure. The failure is strange and I can't determine its source in my initial investigation; the log file (from renaming the task to "make_grid2" can be found here on Hera: /scratch2/BMC/det/kavulich/workdir/update_app_master/step-by-step/expt_dirs/DOT_OR_USCORE/log/make_grid2.log

**Comment by JeffBeck-NOAA** [comment]
@gsketefian, is this still an issue?

**Comment by mkavulich** [comment]
I confirmed that this error still exists in develop, hash 3a2cb827

**Comment by mkavulich** [comment]
This issue is due to logic in ush/load_modules_run_task.sh. The script assumes the runtime module it is looking for in modulefiles/tasks/ is the same as the task name, which means that unless the user has also renamed the modulefile, the runtime module in .

The simplest fix would be to disallow renaming of tasks; right now I can't think of an argument *for* keeping this capability but of course I'm open to ideas.

To keep existing capabilities, we would need to modify ush/load_modules_run_task.sh to look for the original module somehow. But this may be a lot of work for little benefit.

**Comment by mkavulich** [comment]
DTC team suggests renaming of tasks will remain unsupported for now. It would be too much work to either strip this out or fix it, much better to leave as is unless a concrete use case pops up.
